name: "proselint all .md files"
on: pull_request

jobs:
  Proselint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - run: pip install proselint
      - run: proselint *.md
